adjective1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
place = input("Enter a place: ")
verb1 = input("Enter a verb: ")
adjective2 = input("Enter another adjective: ")
noun2 = input("Enter another noun: ")
verb2 = input("Enter another verb: ")
adjective3 = input("Enter another adjective: ")
noun3 = input("Enter another noun: ")
food = input("Enter a food: ")
verb3 = input("Enter another verb:")
emotion = input("Enter an emotion: ")

print("The" + adjective1 + " " + noun1 + " went to the " + place + " to " + verb1 + " with a " + adjective2 + " " + noun2 + ". They " + verb2 + "ed a " + adjective3 + " " + noun3 + " and ate " + food + ". Then, they " + verb3 + "ed home feeling " + emotion + ".The end.")
